language: node_js
node_js:
  - "lts/*"

matrix:
  include:
  - os: linux
    dist: xenial
  - os: osx

sudo: true

env:
  global:
    - VERSION=1.1.1a

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip; fi
  - npm install -g node-gyp
  - node-gyp configure

before_script:
  - npm install
  - npm run rebuild

script:
  - npm run test