# Azure pipelines for building NodeJS & C lib
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install && npm run build && npm run build-ts
    displayName: 'Build the library'
  - script: npm run test && npm run test-ts
    displayName: 'Test the library'